resources:
  jobs:
    - name: bronze_silver_gold_pipeline
      tasks:
        - task_key: bronze_ingestion
          description: "Ingest raw data into Bronze layer"
          notebook_task:
            notebook_path: "/Workspace/Users/vishwa.dharshenee@tredence.com/tredencetry/notebooks/bronze/ingestion_notebook"
          retry_policy:
            max_retries: 1
          timeout_seconds: 1800
          email_notifications:
            on_failure:
              - "vishwa.dharshenee@tredence.com"

        - task_key: silver_transformation
          description: "Transform Bronze → Silver"
          depends_on:
            - task_key: bronze_ingestion
          notebook_task:
            notebook_path: "/Workspace/Users/vishwa.dharshenee@tredence.com/tredencetry/notebooks/silver/silver_notebook"
          retry_policy:
            max_retries: 1
          timeout_seconds: 1800
          email_notifications:
            on_failure:
              - "vishwa.dharshenee@tredence.com"

        - task_key: gold_aggregation
          description: "Aggregate Silver → Gold"
          depends_on:
            - task_key: silver_transformation
          notebook_task:
            notebook_path: "/Workspace/Users/vishwa.dharshenee@tredence.com/tredencetry/notebooks/gold/gold_notebook"
          retry_policy:
            max_retries: 1
          timeout_seconds: 1800
          email_notifications:
            on_failure:
              - "vishwa.dharshenee@tredence.com"
