name: Databricks CI/CD

on:
  push:
    branches:
      - dev
      - qa
      - prod
    paths:
      - 'jobs/*.yml'
      - 'databricks.yml'
      - '.github/workflows/databricks-ci-cd.yml'
  workflow_dispatch:

jobs:
  deploy-to-databricks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: dev
            match: refs/heads/dev
            environment: dev
            target: dev
            databricks_host: https://adb-1089142527401100.0.azuredatabricks.net/

          - branch: qa
            match: refs/heads/qa
            environment: qa
            target: qa
            databricks_host: https://adb-1089142527401100.0.azuredatabricks.net/

          - branch: prod
            match: refs/heads/prod
            environment: prod
            target: prod
            databricks_host: https://adb-1089142527401100.0.azuredatabricks.net/

    steps:
      - name: Check branch match
        if: github.ref == matrix.match
        run: echo "Deploying for branch ${{ matrix.branch }} → target ${{ matrix.target }}"

      - name: Checkout code
        if: github.ref == matrix.match
        uses: actions/checkout@v4

      - name: Azure login
        if: github.ref == matrix.match
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DATABRICKS_CLIENT_ID }}
          tenant-id: ${{ secrets.DATABRICKS_TENANT_ID }}
          subscription-id: ${{ secrets.DATABRICKS_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

      - name: Set Databricks host env
        if: github.ref == matrix.match
        run: echo "DATABRICKS_HOST=${{ matrix.databricks_host }}" >> $GITHUB_ENV

      - name: Set up Databricks CLI
        if: github.ref == matrix.match
        uses: databricks/setup-cli@main

      - name: Validate bundle
        if: github.ref == matrix.match
        run: databricks bundle validate -t ${{ matrix.target }}

      - name: Deploy bundle
        if: github.ref == matrix.match
        run: databricks bundle deploy -t ${{ matrix.target }} --force-lock

